apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-igsd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-igsd
    app.kubernetes.io/part-of: cin4s-839-0001-app
  name: devfile-sample-igsd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-igsd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-igsd
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0001-tenant/cin4s-839-0001-app/devfile-sample-igsd@sha256:9727b9f0f868c0691af10754cf5442a196bbe59ee1ad0ed0b1f783ff101fe9c0
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
